> @Date    : 2020-08-03 17:45:49
>
> @Author  : Lewis Tian (taseikyo@gmail.com)
>
> @Link    : github.com/taseikyo

# How to write and test a Python program

这一章叫你如何测试（pytest）你的 Python 程序，使用给出的 test.py 代码运行结果不对劲：

使用前将 01.test.py 改名为 test.py 再运行。

```bash
D:\GitHub\til\book\tiny-python-projects\src (master -> origin)                               
λ pytest.exe -xv test.py                                                                     
==================================== test session starts ====================================
platform win32 -- Python 3.8.5, pytest-6.0.1, py-1.9.0, pluggy-0.13.1 -- d:\programs\scoop\ap
s\python\3.8.5\python.exe                                                                    
cachedir: .pytest_cache                                                                      
rootdir: D:\GitHub\til\book\tiny-python-projects\src                                         
collected 5 items                                                                            
                                                                                             
test.py::test_exists PASSED                                                            [ 20%]
test.py::test_runnable PASSED                                                          [ 40%]
test.py::test_executable PASSED                                                        [ 60%]
test.py::test_usage FAILED                                                             [ 80%]
                                                                                             
========================================= FAILURES ==========================================
________________________________________ test_usage _________________________________________
                                                                                             
    def test_usage():                                                                        
        """usage"""                                                                          
                                                                                             
        for flag in ["-h", "--help"]:                                                        
            rv, out = getstatusoutput(f"{prg} {flag}")                                       
>           assert rv == 0                                                                   
E           assert 2 == 0                                                                    
E             +2                                                                             
E             -0                                                                             
                                                                                             
test.py:39: AssertionError                                                                   
================================== short test summary info ==================================
FAILED test.py::test_usage - assert 2 == 0                                                   
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
================================ 1 failed, 3 passed in 0.53s ================================
```

可以看到使用 getstatusoutput 函数的返回值并不为 0，不过这是我在 Windows 上跑的。